[package]
name = "penumbra_sdk_wayang"
author.workspace = true
edition.workspace = true
version.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true, features = ["full"] }
clap = {workspace = true, features = ["derive", "env", "color"]}
penumbra-sdk-asset = {workspace = true}
penumbra-sdk-custody = {workspace = true}
penumbra-sdk-proto = {workspace = true, features = ["rpc", "box-grpc"], default-features = true}
penumbra-sdk-view = {workspace = true}
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
toml = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
