[package]
name = "penumbra_sdk_wayang"
author.workspace = true
edition.workspace = true
version.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true, features = ["full"] }
clap = {workspace = true, features = ["derive", "env", "color"]}
serde = { workspace = true, features = ["derive"] }
toml = { workspace = true }
