# Example configuration file for wayang

# The trading pair to provide liquidity for
pair = "UM/USDC"

# Account index to use (should be > 0 for safety)
account = 1


# RPC endpoint URL
grpc_url = "https://grpc.testnet.penumbra.zone"

# View service endpoint URL
view_service = "http://localhost:8080"