#!/bin/bash
# Utility script to scrape LoadBalancer IPs from k8s Service objects,
# polling for ready state, so that the deployment can be re-run
# with IP information as input values, optionally version-controlled.
set -euo pipefail

if [[ $# -lt 1 ]] ; then
    >&2 echo "ERROR: found no Helm release to target"
    >&2 echo "Run 'helm list' to see available options"
    >&2 echo "Usage: $0 <helm_release>"
    exit 1
fi

# Declare monikers for nodes on the network.
# These monikers will be added to the generated vars file,
# alongside the IP info. Here we use notable asteroids,
# reserving moons for testnet names.
node_names=(ceres-seed vesta pallas hygiea)

HELM_RELEASE="${1:-}"
shift 1
vars_file="${PWD}/helmfile.d/vars/${HELM_RELEASE}-ips.yml"

if [[ ! -e "$vars_file" ]] ; then
    touch "$vars_file"
fi

# Poll k8s API for loadbalancer IPs, for a specific helm deployment.
function get_ips() {
    if ! kubectl get svc \
        -l "app.kubernetes.io/instance=${HELM_RELEASE},app.kubernetes.io/component=p2p" \
        -o json | jq '.items[].status.loadBalancer.ingress[].ip' -r 2>/dev/null ; then
    # if the scrape failed, emit an empty string, so caller can wait.
    echo "";
    fi
}

ip_info="$(get_ips)"
printf "Waiting for LoadBalancer IPs for Helm release '%s'" "$HELM_RELEASE"
while [[ -z "$ip_info" ]] ; do
    printf '.'
    sleep 5
    ip_info="$(get_ips)"
done
printf ' done!\n'

# Write out a YAML file suitable for using as input values in a Helm chart.
# This format is very specific to values format required by the given Helm chart.
function generate_yaml_penumbra_nodes() {
    printf 'nodes:\n'
    counter=0
    while read -r ip_addr ; do
        node_name="${node_names[$counter]}"
        cat <<EOF
  - external_address: ${ip_addr}:26656
    moniker: ${node_names[$counter]}
EOF
    # Special handling for seed nodes: if moniker declares it's a seed,
    # it's a seed.
    if [[ $node_name =~ seed ]] ; then
        printf '    seed_mode: true\n'
    fi
    counter="$(( counter + 1 ))"
    done <<< "$ip_info"
}

generate_yaml_penumbra_nodes > "$vars_file"
echo "IP info written to $vars_file for $HELM_RELEASE"
