#!/bin/bash
# Utility script to download a specific version of grpcurl for use
# in testing Penumbra, specifically in validating the gRPC reflection
# APIs via integration tests.
# Designed to be used in CI contexts, to bootstrap a testing setup quickly.
set -euo pipefail


# Sane defaults
GRPCURL_VERSION="${GRPCURL_VERSION:-1.9.1}"

# Download and extract
grpcurl_download_url="https://github.com/fullstorydev/grpcurl/releases/download/v${GRPCURL_VERSION}/grpcurl_${GRPCURL_VERSION}_linux_x86_64.tar.gz"
grpcurl_temp_dir="$(mktemp -d)"
pushd "$grpcurl_temp_dir" > /dev/null
curl -sSfL -O "$grpcurl_download_url"
tar -xzf "grpcurl_${GRPCURL_VERSION}_linux_x86_64.tar.gz" grpcurl
trap 'rm -r "$grpcurl_temp_dir"' EXIT

# Try to write to system-wide location.
if [[ -w /usr/local/bin/ ]] ; then
    mv -v grpcurl /usr/local/bin/
else
    grpcurl_install_dir="${HOME:?}/bin"
    >&2 echo "WARNING: /usr/local/bin/ not writable, installing grpcurl to $grpcurl_install_dir"
    mkdir -p "$grpcurl_install_dir"
    mv -v grpcurl "${grpcurl_install_dir}/"
    export PATH="$PATH:$grpcurl_install_dir"
fi

# Sanity checks
echo "Checking that grpcurl is installed:"
which grpcurl
grpcurl --version
