#!/usr/bin/env bash
# CI script to set a given testnet deployment environment in "maintenaceMode",
# essentially stopping both pd and cometbft, so that an interactive environment
# can be created, without the services writing to local state.
set -euo pipefail

# script expects to be in deployments/ dir
if [[ ! -e ci.sh ]] ; then
    >&2 echo "ERROR: script should be run from inside 'deployments/' dir"
    exit 1
fi

TO_VERSION="${TO_VERSION:-}"
if [[ -z "$TO_VERSION" ]] ; then
    >&2 echo "ERROR: TO_VERSION must be set with an explicit version"
    exit 1
fi

# Default to devnet to avoid touching testnet unless explicitly requested.
HELM_RELEASE="${HELM_RELEASE:-penumbra-devnet}"

# Set maintenaceMode=true.
function enable_maintenance_mode() {
    >&2 echo "Enabling maintenance mode on ${HELM_RELEASE}..."
    helmfile --quiet apply -f "helmfile.d/${HELM_RELEASE}.yaml" --args \
        --set=maintenanceMode=true \
        --set="image.tag=${TO_VERSION}"

    >&2 echo "Waiting for maintenance mode..."
    kubectl rollout status statefulset \
        -l "app.kubernetes.io/part-of=${HELM_RELEASE}, app.kubernetes.io/component in (fullnode, genesis-validator)"

    >&2 echo "Done, the statefulsets are paused now"
}

# Main entrypoint
function main() {
    # uncomment at will
    enable_maintenance_mode
}

main
exit 0
