#!/usr/bin/env bash
# Helper script to prepare a localhost postgres instance,
# provisioned via nix, for ingesting ABCI events from CometBFT for Penumbra.
set -euo pipefail


# The Nix env will add the postgres share directory to XDG_DATA_DIRS.
# Let's pluck that out of the dir listing env vars, so we can copy files out of it
# to a writable location.
postgres_share_dir="$(echo "$XDG_DATA_DIRS" | perl -npE 's/:/\n/g' | grep postgresql | tail -n 1)"

if [[ -z "${postgres_share_dir}" ]] ; then
    >&2 "ERROR: could not find postgres dir in XDG_DATA_DIRS"
    exit 1
fi

# Set up a write-friendly directory for postgres state.
# The nix store is read-only by default, so add write capability to copy.
postgres_config_dir="$HOME/.penumbra/network_data/postgresql"
# While debugging it may be useful to nuke the dir between runs.
# rm -rf "$postgres_config_dir"
mkdir -p "${postgres_config_dir}"

# If PG_VERSION exists, then the initdb cmd has already been run.
if [[ -e "${postgres_config_dir}/PG_VERSION" ]] ; then
    >&2 echo "Postgres database already configured in '${postgres_config_dir}', skipping initdb..."
else
    pg_ctl initdb --pgdata "${postgres_config_dir}"
fi
