#!/usr/bin/env bash
# Generate code for Rust & Go from proto definitions.

set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"

# Purge the output dirs, to ensure that the codegen is complete:
# if upstream removed files, we want them removed from all outputs, too.
echo "Cleaning output dirs..."
for d in proto/rust-vendored crates/proto/src/gen ; do
    rm -r "${repo_root}/${d}/"
    mkdir -p "${repo_root}/${d}/"
done

echo "Pulling proto dependencies from BSR..."
pushd "${repo_root}/proto/"
# Make sure the lockfile is up to date.
buf dep update penumbra

# Pull our vendored cosmos/IBC proto defs so we can get reflection for service definitions.
# The penumbra dependencies will override some of these.
buf export buf.build/noble-assets/forwarding:5a8609a6772d417584a9c60cd8b80881 --output rust-vendored/
buf export buf.build/cosmos/cosmos-sdk:e7a85cef453e4b999ad9aff8714ae05f --output rust-vendored/
buf export buf.build/cosmos/ibc:7ab44ae956a0488ea04e04511efa5f70 --output rust-vendored/

buf export penumbra --output rust-vendored/

# Remove the re-exported Penumbra proto defs, since we version control
# those directly in this repo, and don't need to duplicate them as output.
rm -rf rust-vendored/penumbra/

echo "Generating rust code..."
pushd "${repo_root}/tools/proto-compiler"
cargo run
popd

echo "Finished! Consider running a 'cargo check --release' to confirm builds still work."
