#!/usr/bin/env bash
# Rebuild Rust crate documentation.
#
# We use a custom build process for the Rust API docs, in order to provide
# a landing page that lists all relevant crates on a single page.
set -euo pipefail

# Set:
# --enable-index-page -Zunstable-options
#     to generate the index page
# --cfg docsrs
#     to enable nightly-only doc_cfg annotations
export RUSTDOCFLAGS="--enable-index-page -Zunstable-options --cfg docsrs"

# Explicitly specify which crates should be included.
# Guidelines:
# - workspace crates are included
# - git dependencies are included
# - published crates are excluded
# Doing this in one go is useful because the JSON file with search
# indexes is overwritten on each cargo doc invocation.

# The nix version of `cargo` does not support the `+nightly` flag.
# There's a nix devShell specifically for nightly Rust, that's used in CI.
# We'll still support non-nix Rust nightlies, though.
nightly_opt=""
if [[ -z "${IN_NIX_SHELL:-}" ]] ; then
  nightly_opt="+nightly"
fi
cargo $nightly_opt doc --no-deps \
  -p ark-ff \
  -p ark-serialize \
  -p cnidarium \
  -p cnidarium-component \
  -p cometindex \
  -p decaf377-fmd \
  -p decaf377-ka \
  -p decaf377-rdsa \
  -p decaf377@0.10.1 \
  -p ibc-types \
  -p jmt \
  -p pcli \
  -p pclientd \
  -p pd \
  -p pmonitor \
  -p penumbra-sdk-app \
  -p penumbra-sdk-asset \
  -p penumbra-sdk-community-pool \
  -p penumbra-sdk-custody \
  -p penumbra-sdk-custody-ledger-usb \
  -p penumbra-sdk-dex \
  -p penumbra-sdk-distributions \
  -p penumbra-sdk-fee \
  -p penumbra-sdk-governance \
  -p penumbra-sdk-ibc \
  -p penumbra-sdk-keys \
  -p penumbra-sdk-measure \
  -p penumbra-sdk-mock-consensus \
  -p penumbra-sdk-mock-tendermint-proxy \
  -p penumbra-sdk-mock-client \
  -p penumbra-sdk-num \
  -p penumbra-sdk-proof-params \
  -p penumbra-sdk-proof-setup \
  -p penumbra-sdk-proto \
  -p penumbra-sdk-sct \
  -p penumbra-sdk-shielded-pool \
  -p penumbra-sdk-stake \
  -p penumbra-sdk-tct \
  -p penumbra-sdk-transaction \
  -p penumbra-sdk-txhash \
  -p penumbra-sdk-view \
  -p penumbra-sdk-wallet \
  -p pindexer \
  -p poseidon-permutation \
  -p poseidon377 \
  -p tendermint \
  -p tendermint-config \
  -p tower-abci \

>&2 echo "Copying newly built index file to docroot for deployment"
cp -v target/doc/index.html docs/rustdoc/index.html
