#!/usr/bin/env bash
# Rebuild Rust crate documentation
set -euo pipefail

# Set:
# --enable-index-page -Zunstable-options
#     to generate the index page
# --cfg docsrs
#     to enable nightly-only doc_cfg annotations
export RUSTDOCFLAGS="--enable-index-page -Zunstable-options --cfg docsrs"

# Explicitly specify which crates should be included.
# Guidelines:
# - workspace crates are included
# - git dependencies are included
# - published crates are excluded
# Doing this in one go is useful because the JSON file with search
# indexes is overwritten on each cargo doc invocation.

cargo +nightly doc --no-deps \
  -p ark-ff \
  -p ark-serialize \
  -p cnidarium \
  -p cnidarium-component \
  -p decaf377-fmd \
  -p decaf377-ka \
  -p decaf377-rdsa \
  -p decaf377@0.5.0 \
  -p ibc-types \
  -p jmt \
  -p pcli \
  -p pclientd \
  -p pd \
  -p penumbra-app \
  -p penumbra-asset \
  -p penumbra-community-pool \
  -p penumbra-custody \
  -p penumbra-dex \
  -p penumbra-distributions \
  -p penumbra-fee \
  -p penumbra-governance \
  -p penumbra-ibc \
  -p penumbra-keys \
  -p penumbra-measure \
  -p penumbra-num \
  -p penumbra-proof-params \
  -p penumbra-proof-setup \
  -p penumbra-proto \
  -p penumbra-sct \
  -p penumbra-shielded-pool \
  -p penumbra-stake \
  -p penumbra-tct \
  -p penumbra-transaction \
  -p penumbra-txhash \
  -p penumbra-view \
  -p penumbra-wallet \
  -p poseidon-paramgen \
  -p poseidon-permutation \
  -p poseidon377 \
  -p tendermint \
  -p tendermint-config \
  -p tower-abci \

>&2 echo "Copying newly built index file to version-controlled path:"
cp -v target/doc/index.html docs/rustdoc/index.html
