#!/usr/bin/env bash
# Utility script to check whether a Penumbra state dir exists,
# and exit non-zero if so. Useful to reuse throughout a variety
# of CI scripts for the Penumbra monorepo.
set -euo pipefail


# Fail fast if testnet dir exists, otherwise `cargo run ...` will block
# for a while, masking the error.
if [[ -d ~/.penumbra/network_data ]] ; then
    >&2 echo "ERROR: network data directory exists at ~/.penumbra/network_data"
    >&2 echo "Not removing this directory automatically; to remove, run: pd network unsafe-reset-all"
    exit 1
fi
