[package]
name = "penumbra-sdk-keys"
authors = {workspace = true}
repository = {workspace = true}
description = "Key data structures and core utilities for Penumbra"
version = {workspace = true}
license = {workspace = true}
edition = {workspace = true}

[features]
default = []
parallel = ["penumbra-sdk-tct/parallel", "ark-ff/parallel", "poseidon377/parallel", "decaf377-rdsa/parallel", "ark-std/parallel", "ark-r1cs-std/parallel", "decaf377/parallel"]

[dependencies]
aes = "0.8.1"
anyhow = {workspace = true}
ark-ff = {workspace = true, default-features = false}
ark-r1cs-std = {workspace = true, default-features = false}
ark-relations = {workspace = true}
ark-serialize = {workspace = true}
ark-std = {workspace = true, default-features = false}
base64 = {workspace = true}
bech32 = {workspace = true}
bip32 = "0.5"
blake2b_simd = {workspace = true}
bytes = {workspace = true}
chacha20poly1305 = {workspace = true}
decaf377 = {workspace = true, features = ["r1cs"], default-features = true}
decaf377-fmd = {workspace = true}
decaf377-ka = {workspace = true}
decaf377-rdsa = {workspace = true}
derivative = {workspace = true}
ethnum = {workspace = true}
f4jumble = "0.1.0"
hex = {workspace = true}
hmac = "0.12.0"
ibig = {workspace = true}
num-bigint = {workspace = true}
once_cell = {workspace = true}
pbkdf2 = "0.12.0"
penumbra-sdk-asset = {workspace = true, default-features = true}
penumbra-sdk-proto = {workspace = true, default-features = true}
penumbra-sdk-tct = {workspace = true, features = ["r1cs"], default-features = true}
poseidon377 = {workspace = true, features = ["r1cs"]}
rand = {workspace = true}
rand_core = {workspace = true, features = ["getrandom"]}
regex = {workspace = true}
serde = {workspace = true, features = ["derive"]}
sha2 = {workspace = true}
thiserror = {workspace = true}
tracing = {workspace = true}

[dev-dependencies]
proptest = {workspace = true}
serde_json = {workspace = true}
num-traits = {workspace = true}
getrandom = {workspace = true}
