ARG GRAFANA_VERSION="10.1.5"
FROM docker.io/grafana/grafana:${GRAFANA_VERSION}
COPY deployments/config/grafana/provisioning/ /etc/grafana/provisioning/
COPY deployments/config/grafana/grafana.ini /etc/grafana/grafana.ini
COPY deployments/config/grafana/dashboards/ /var/lib/grafana/dashboards/
