[package]
name = "penumbra-sdk-community-pool"
authors = {workspace = true}
repository = {workspace = true}
description = "Community Pool component implementation for Penumbra"
version = {workspace = true}
license = {workspace = true}
edition = {workspace = true}

[features]
component = [
    "cnidarium-component",
    "cnidarium",
    "tonic",
    "penumbra-sdk-proto/cnidarium",
    "penumbra-sdk-shielded-pool/component",

    "async-stream",
]
default = ["component"]
docsrs = []

[dependencies]
anyhow = {workspace = true}
ark-ff = {workspace = true, default-features = false}
async-trait = {workspace = true}
async-stream = {workspace = true, optional = true}
base64 = {workspace = true}
blake2b_simd = {workspace = true}
cnidarium = {workspace = true, optional = true, default-features = true}
cnidarium-component = {workspace = true, optional = true, default-features = true}
futures = {workspace = true}
hex = {workspace = true}
metrics = {workspace = true}
once_cell = {workspace = true}
pbjson-types = {workspace = true}
penumbra-sdk-asset = {workspace = true, default-features = false}
penumbra-sdk-keys = {workspace = true, default-features = false}
penumbra-sdk-num = {workspace = true, default-features = false}
penumbra-sdk-proto = {workspace = true, default-features = false}
penumbra-sdk-sct = {workspace = true, default-features = false}
penumbra-sdk-shielded-pool = {workspace = true, default-features = false}
penumbra-sdk-txhash = {workspace = true, default-features = false}
prost = {workspace = true}
serde = {workspace = true, features = ["derive"]}
sha2 = {workspace = true}
tendermint = {workspace = true}
tendermint-light-client-verifier = {workspace = true}
tonic = {workspace = true, optional = true}
tracing = {workspace = true}

[dev-dependencies]
tokio = {workspace = true, features = ["full"]}
