[package]
name = "decaf377-fmd"
license = {workspace = true}
version = {workspace = true}
edition = {workspace = true}
authors = {workspace = true}
repository = {workspace = true}
description = "An implementation of Fuzzy Message Detection (FMD)."

[[bench]]
name = "fmd"
harness = false


[features]
default = ["rand", "ark-ff", "ark-serialize"]
rand = ["decaf377/rand", "rand_core"]
arkworks = ["decaf377/arkworks"]

[dependencies]
ark-ff = {workspace = true, default-features = false, optional = true}
ark-serialize = {workspace = true, optional = true}
bitvec = {workspace = true}
blake2b_simd = {workspace = true}
decaf377 = {workspace = true, default-features = false}
rand_core = {workspace = true, optional = true}
thiserror = {workspace = true}

[target.'cfg(target_arch = "wasm32")'.dependencies]
rand_core = {workspace = true, optional = true}

[dev-dependencies]
criterion = {workspace = true, features = ["html_reports"]}
proptest = {workspace = true}
rand_core = {workspace = true, features = ["getrandom"]}
