{
 "title": "ABCI",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Something? ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(tendermint_abci_connection_method_timing_count[5m])) by (method)"
    }
   ]
  },
  {
   "title": "BeginBlock",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(tendermint_abci_connection_method_timing_bucket{method=\"begin_block\"}[5m])))"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(tendermint_abci_connection_method_timing_bucket{method=\"begin_block\"}[5m])))"
    }
   ]
  },
  {
   "title": "DeliverTx",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(tendermint_abci_connection_method_timing_bucket{method=\"deliver_tx\"}[5m])))"
    }
   ]
  },
  {
   "title": "EndBlock",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(tendermint_abci_connection_method_timing_bucket{method=\"end_block\"}[5m])))"
    }
   ]
  },
  {
   "title": "Commit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(tendermint_abci_connection_method_timing_bucket{method=\"commit\"}[5m])))"
    }
   ]
  }
 ]
}