{
 "title": "Consensus",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Validators",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators",
     "legendFormat": "Missing Validators"
    },
    {
     "expr": "tendermint_consensus_validators",
     "legendFormat": "Validators"
    }
   ]
  },
  {
   "title": "Blocks Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(tendermint_consensus_latest_block_height[5m])"
    }
   ]
  },
  {
   "title": "Consensus Rounds",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "targets": [
    { "expr": "tendermint_consensus_rounds" }
   ]
  }
 ]
}