[package]
name = "penumbra-proto-compiler"
# We don't use `{ workspace = true }` attributes, because the proto-compiler tool
# is excluded from the workspace.
authors    = ["Penumbra Labs <team@penumbralabs.xyz"]
description = "The Penumbra Protobuf Compilation Helper"
edition = "2021"
homepage   = "https://penumbra.zone"
license    = "MIT OR Apache-2.0"
publish = false
repository = "https://github.com/penumbra-zone/penumbra"
version = "0.1.0"

[dependencies]
anyhow = "1"
ibc-proto = { version = "0.51.1" }
ics23 = "0.12.0"
pbjson = "0.7.0"
pbjson-build = "0.7.0"
pbjson-types = "0.7.0"
prost = "0.13.3"
prost-build = "0.13.3"
prost-types = "0.13.3"
tempfile = "3"
tonic-build = { version = "0.12.3", features = ["cleanup-markdown"] }
