[package]
name = "penumbra-sdk-num"
authors = {workspace = true}
repository = {workspace = true}
description = "Numerical data structures and implementations used by Penumbra"
version = {workspace = true}
license = {workspace = true}
edition = {workspace = true}

[features]
default = ["rand", "proto", "r1cs"]
parallel = ["ark-ff/parallel", "ark-groth16/parallel", "ark-std/parallel", "ark-r1cs-std/parallel", "decaf377/parallel"]
rand = ["std", "rand_core", "dep:rand", "decaf377/rand"]
proto = ["penumbra-proto", "dep:serde"]
r1cs = [
    "std",
    "decaf377/r1cs",
    "dep:ark-ff",
    "dep:ark-groth16",
    "dep:ark-r1cs-std",
    "dep:ark-relations",
    "dep:ark-serialize",
    "dep:ark-snark",
    "dep:ark-std",
    "dep:ethnum",
    "dep:ibig",
]
std = [
  "ark-ff/std",
  "dep:thiserror",
]

[dependencies]
anyhow = {workspace = true}
ark-ff = {workspace = true, optional = true}
ark-groth16 = {workspace = true, optional = true}
ark-r1cs-std = {workspace = true, optional = true}
ark-relations = {workspace = true, optional = true}
ark-serialize = {workspace = true, optional = true}
ark-snark = {workspace = true, optional = true}
ark-std = {workspace = true, default-features = false, optional = true}
decaf377 = {workspace = true, default-features = false}
ethnum = {workspace = true, optional = true}
ibig = {workspace = true, optional = true}
penumbra-proto = {workspace = true, default-features = false, optional = true}
rand = {workspace = true, optional = true}
rand_core = {workspace = true, features = ["getrandom"], optional = true}
serde = {workspace = true, features = ["derive"], optional = true}
thiserror = {workspace = true, optional = true}

[dev-dependencies]
proptest = {workspace = true}
serde_json = {workspace = true}
