[package]
name = "penumbra-sdk-num"
authors = {workspace = true}
repository = {workspace = true}
description = "Numerical data structures and implementations used by Penumbra"
version = {workspace = true}
license = {workspace = true}
edition = {workspace = true}

[features]
default = []
parallel = ["ark-ff/parallel", "decaf377-rdsa/parallel", "ark-groth16/parallel", "ark-std/parallel", "ark-r1cs-std/parallel", "decaf377/parallel"]
rand = ["rand_core", "dep:rand"]
proto = ["penumbra-proto"]
r1cs = ["decaf377/r1cs",
    "dep:ark-ff",
    "dep:ark-groth16",
    "dep:ark-r1cs-std",
    "dep:ark-relations",
    "dep:ark-serialize",
    "dep:ark-snark",
    "dep:ark-std",
]
std = ["rand", "proto", "r1cs"]

[dependencies]
anyhow = {workspace = true}
ark-ff = {workspace = true, default-features = false, optional = true}
ark-groth16 = {workspace = true, default-features = false, optional = true}
ark-r1cs-std = {workspace = true, default-features = false, optional = true}
ark-relations = {workspace = true, optional = true}
ark-serialize = {workspace = true, optional = true}
ark-snark = {workspace = true, optional = true}
ark-std = {workspace = true, default-features = false, optional = true}
base64 = {workspace = true}
bech32 = {workspace = true}
#blake2b_simd = {workspace = true}
#bytes = {workspace = true}
decaf377 = {workspace = true, default-features = true}
#decaf377-fmd = {workspace = true, default-features = true}
decaf377-rdsa = {workspace = true, default-features = true}
#derivative = {workspace = true}
ethnum = {workspace = true}
#hex = {workspace = true}
ibig = {workspace = true}
#num-bigint = {workspace = true}
#once_cell = {workspace = true}
penumbra-proto = {workspace = true, default-features = true, optional = true}
rand = {workspace = true, optional = true}
rand_core = {workspace = true, features = ["getrandom"], optional = true}
#regex = {workspace = true}
serde = {workspace = true, features = ["derive"]}
#sha2 = {workspace = true}
thiserror = {workspace = true}
#tracing = {workspace = true}

[dev-dependencies]
proptest = {workspace = true}
serde_json = {workspace = true}
