{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "penumbra.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ include "penumbra.fullname" . }}-ingress-ip
    networking.gke.io/managed-certificates: {{ include "penumbra.fullname" . }}-ingress-cert
    kubernetes.io/ingress.class: "gce"
  labels:
    {{- include "penumbra.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.hosts.rpc }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                # Service name points to fullnode-0; assumes at least 1 fn
                name: {{ include "penumbra.fullname" . }}-p2p-fn-0
                port:
                  number: 26657
    - host: {{ .Values.ingress.hosts.grpc }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "penumbra.fullname" . }}-p2p-fn-0
                port:
                  number: 8080
{{- end }}
