[package]
name = "penumbra-sdk-asset"
authors = {workspace = true}
repository = {workspace = true}
description = "Core asset data structures for Penumbra"
version = {workspace = true}
license = {workspace = true}
edition = {workspace = true}

[features]
default = ["rand"]
parallel = [
    "ark-ff/parallel",
    "poseidon377/parallel",
    "decaf377-rdsa/parallel",
    "ark-std/parallel",
    "ark-r1cs-std/parallel",
    "decaf377/parallel",
]
rand = [
    "dep:rand_core",
    "dep:rand",
    "dep:getrandom",
    "decaf377/rand",
    "decaf377-fmd/rand", 
    "decaf377-rdsa/rand",
    "penumbra-num/rand",
]

[dependencies]
anyhow = {workspace = true}
ark-ff = {workspace = true, default-features = false}
ark-r1cs-std = {workspace = true, default-features = false}
ark-relations = {workspace = true}
ark-serialize = {workspace = true}
ark-std = {workspace = true, default-features = false}
base64 = {workspace = true}
blake2b_simd = {workspace = true}
decaf377 = {workspace = true, features = ["r1cs"], default-features = false}
decaf377-fmd = {workspace = true, default-features = false}
decaf377-rdsa = {workspace = true, default-features = false}
getrandom = {workspace = true, features = ["js"], optional = true}
once_cell = {workspace = true}
penumbra-num = {workspace = true, features = ["r1cs", "proto"], default-features = false}
penumbra-proto = {workspace = true, default-features = false}
poseidon377 = {workspace = true, features = ["r1cs"], default-features = false}
rand = {workspace = true, optional = true}
rand_core = {workspace = true, features = ["getrandom"], optional = true}
regex = {workspace = true}
serde = {workspace = true, features = ["derive"]}
serde_with = {workspace = true}
thiserror = {workspace = true}
pbjson-types = {workspace = true}
lazy_static = "1.5.0"

[dev-dependencies]
proptest = {workspace = true}
serde_json = {workspace = true}
getrandom = {workspace = true}
