{{ $count := (.Values.count | int) }}
{{ range $i,$e := until $count }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "val-secrets-{{$i}}"
data:
{{ $basePath := printf "pdcli/.penumbra/testnet_data/node%d/tendermint/config" $i }}
{{ $privValPath := printf "%s/priv_validator_key.json" $basePath }}
{{- "priv_validator_key.json" | indent 2 -}}{{ print ": "}}{{ $.Files.Get $privValPath | b64enc }}
{{ $nodeKeyPath := printf "%s/node_key.json" $basePath }}
{{- "node_key.json" | indent 2 -}}{{ print ": "}}{{ $.Files.Get $nodeKeyPath | b64enc }}
{{ $validatorCustodyPath := printf "%s/validator_custody.json" $basePath }}
{{- "validator_custody.json" | indent 2 -}}{{ print ": "}}{{ $.Files.Get $validatorCustodyPath | b64enc }}
{{ end }}
