#!/bin/bash
# Configure relayer from scratch; nukes any previous state, so use with caution.
# Follows the config steps documented in relayer README:
# https://github.com/cosmos/relayer/
set -euo pipefail

if [[ $# -lt 2 ]] ; then
    >&2 echo "ERROR: networks not specified. Use, e.g., 'penumbra-testnet penumbra-preview'."
    >&2 echo "Usage: $0 <network-1> <network-2>"
    exit 1
fi

chain_a="$1"
chain_b="$2"
shift 2


rm -rf ~/.relayer
rly config init --memo "Automatic IBC for Penumbra, via relayer"

>&2 echo "Adding chain specs to relayer config..."
rly chains add-dir configs/

# Ideally we wouldn't need to bother with generating keys for the relayer paths,
# because Penumbra hasn't implemented fees yet, so there's no need for a wallet to pay out of.
# If we skip keygen, though, then `rly transact link <path>` shows an error:
#
#   Error: key default not found on src chain penumbra-testnet-carme-dac8be27
>&2 echo "Generating key for $chain_a:"
rly keys add "$chain_a" default
>&2 echo "Generating key for $chain_b:"
rly keys add "$chain_b" default

# Configure paths. We can't fetch from an external registry, so we'll
# need to munge the YAML config directly. See docs at
# https://github.com/cosmos/relayer/blob/main/docs/create-path-across-chain.md
chain_a_id="$(jq -r '.value["chain-id"]' "configs/${chain_a}.json")"
chain_b_id="$(jq -r '.value["chain-id"]' "configs/${chain_b}.json")"
rly paths new "$chain_a_id" "$chain_b_id" penumbra_path

>&2 echo "Emitting status info:"
rly chains list
rly paths list
