#!/bin/bash
# Configure relayer from scratch; nukes any previous state, so use with caution.
# Follows the config steps documented in relayer README:
# https://github.com/cosmos/relayer/
set -euo pipefail

rm -rf ~/.relayer
rly config init --memo "Automatic IBC for Penumbra, via relayer"

>&2 echo "Adding chain specs to relayer config..."
rly chains add-dir configs/

# Ideally we wouldn't need to bother with generating keys for the relayer paths,
# because Penumbra hasn't implemented fees yet, so there's no need for a wallet to pay out of.
# If we skip keygen, though, then `rly transact link <path>` shows an error:
#
#   Error: key default not found on src chain penumbra-testnet-carme-dac8be27
for chain in $(rly chains list --json | jq 'keys | join("\n")' -r) ; do
    >&2 echo "Generating key for $chain"
    rly keys add "$chain" default
done

function create_paths() {
    if [[ $# -lt 3 ]] ; then
        >&2 echo "ERROR: networks not specified. Use, e.g., 'penumbra-testnet penumbra-preview'."
        >&2 echo "Usage: $0 <network-1> <network-2> <path-name>"
        return 1
    fi

    local chain_a="$1"
    local chain_b="$2"
    local path_name="$3"
    shift 3

    # Make sure requested chain configs exist locally. This won't be necessary
    # when the referenced chains exist in the upstream public chain registry.
    if [[ ! -e "configs/${chain_a}.json" ]]; then
        >&2 echo "ERROR: file not found: configs/${chain_a}.json"
        return 2
    elif [[ ! -e "configs/${chain_b}.json" ]]; then
        >&2 echo "ERROR: file not found: configs/${chain_b}.json"
        return 2
    fi

    chain_a_id="$(jq -r '.value["chain-id"]' "configs/${chain_a}.json")"
    chain_b_id="$(jq -r '.value["chain-id"]' "configs/${chain_b}.json")"
    rly paths new "$chain_a_id" "$chain_b_id" "$path_name"
}

# Create Penumbra-only path, between preview and testnet. Works!
create_paths penumbra-testnet penumbra-preview penumbra_path

# Create paths between Penumbra and/or other Cosmos-adjacent testnets.
# These are not working yet, so commenting them out by default.
#
# create_paths penumbra-preview babylon-testnet babylon
# create_paths osmosis-testnet babylon-testnet osmosis
# create_paths osmosis-testnet cosmwasm-testnet osmosis-wasm
# create_paths osmosis-testnet celestia-testnet osmosis-celestia

>&2 echo "Emitting status info:"
rly chains list
rly paths list
