all:
   just configs
   just run

configs:
    ./generate-configs preview
    ./generate-configs testnet

run:
    ./configure-relayer penumbra-testnet penumbra-preview penumbra_path
    ./configure-relayer penumbra-preview babylon-testnet babylon
    ./run-relayer
