#!/bin/bash
# Wrapper script to use `grpcurl` to query Penumbra pd over HTTPS.
#
# Requires grpcurl to be installed locally. Assumes running from the
# top-level dir of the penumbra git repo.
set -euo pipefail


if [[ $# -lt 1 ]] ; then
    >&2 echo "Usage: $0 <protobuf_method> ; e.g."
    >&2 echo "$0 penumbra.client.v1alpha1.ObliviousQueryService/ChainParameters"
    exit 1
fi


# Disable linting on the clever find/xargs combo
# shellcheck disable=SC2046
grpcurl \
    -import-path proto/proto/ \
    -import-path proto/ibc-go-vendor \
    $(find proto/proto -type f -iname '*.proto' | xargs -r -n 1 printf ' -proto %s ') \
    grpc.testnet-preview.penumbra.zone:443 \
    "$@"
