#!/bin/bash
# Rebuild Rust crate documentation
set -euo pipefail


# The index.html can only be rebuilt via nightly rust.
REGENERATE_INDEX="${REGENERATE_INDEX:-}"
if [[ -n "$REGENERATE_INDEX" ]]; then
    >&2 echo "Rebuilding index.html via nightly cargo..."
    export RUSTDOCFLAGS="--enable-index-page -Zunstable-options"
    nightly_opt="+nightly"
else
    >&2 echo "Env var REGENERATE_INDEX not found, skipping index.html creation..."
    nightly_opt=""
fi

# Explicitly specify which crates should be included.
# Guidelines:
# - workspace crates are included
# - git dependencies are included
# - published crates are excluded
# Doing this in one go is useful because the JSON file with search
# indexes is overwritten on each cargo doc invocation.
#
# When updating, remember to run with REGENERATE_INDEX=1.
# See docs/rustdoc/README.md for more info.

# Silence shellcheck warning on 'nightly_opt' being an empty string.
# shellcheck disable=SC2086
cargo $nightly_opt doc --no-deps \
  -p tendermint \
  -p tower-abci \
  -p jmt@0.2.0 \
  -p ark-ff \
  -p ark-serialize \
  -p ark-sponge \
  -p poseidon377 \
  -p https://github.com/rust-lang/crates.io-index#poseidon-paramgen@0.1.0 \
  -p poseidon-permutation \
  -p https://github.com/penumbra-zone/decaf377#0.1.0 \
  -p decaf377-rdsa \
  -p decaf377-fmd \
  -p decaf377-ka \
  -p penumbra-proto \
  -p penumbra-chain \
  -p penumbra-component \
  -p penumbra-crypto \
  -p penumbra-custody \
  -p penumbra-measure \
  -p penumbra-storage \
  -p penumbra-tct \
  -p penumbra-transaction \
  -p penumbra-wallet \
  -p penumbra-view \
  -p pd \
  -p pcli

if [[ -n "$REGENERATE_INDEX" ]]; then
    >&2 echo "Copying newly built index file to version-controlled path:"
    cp -v target/doc/index.html docs/rustdoc/index.html
fi
