[package]
name = "penumbra-sdk-parameter-setup"
description = "Penumbra proof parameters setup utilities"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = true
repository = { workspace = true }
version = { workspace = true }

[dependencies]
ark-groth16 = { workspace = true }
ark-serialize = { workspace = true }
decaf377 = { workspace = true, features = ["r1cs"] }
penumbra-sdk-community-pool = { workspace = true , features = ["component"] }
penumbra-sdk-dex = { workspace = true }
penumbra-sdk-governance = { workspace = true }
penumbra-sdk-proof-params = { workspace = true }
penumbra-sdk-proof-setup = { workspace = true, features = ["parallel"] }
penumbra-sdk-shielded-pool = { workspace = true, features = ["parallel"] }
penumbra-sdk-stake = { workspace = true, features = ["component"] }
rand_core = { workspace = true }
