{
 "title": "pd performance",
 "description": "Metrics specific to how pd performs under load.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "pd CPU usage",
   "type": "timeseries",
   "description": "The amount of CPU seconds used by pd, as rate in 1m intervals. How to represent as percentage of total available compute?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(pd_process_cpu_seconds_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "pd async sleep drift",
   "type": "timeseries",
   "description": "Tracks drift in the async runtime's timer, in microseconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(pd_async_sleep_drift_microseconds[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "pd memory usage",
   "type": "timeseries",
   "description": "How much RAM pd is using",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pd_process_resident_memory_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "pd filehandle utilization",
   "type": "timeseries",
   "description": "Tower ABCI uses a lot of filehandles, and defaults of 1024 are often too low. Track actual utilization.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "pd_process_open_fds", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}