{
 "title": "sync",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "# of served CBs (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(penumbra_component_compact_block_compact_block_range_served_total[5m])"
    }
   ]
  },
  {
   "title": "# of active sync connections (pd)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "penumbra_component_compact_block_compact_block_range_active_connections"
    }
   ]
  },
  {
   "title": "Storage lookups nonverif",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(penumbra_storage_nonverifiable_get_raw_duration_seconds_sum[5m]) / rate(penumbra_storage_nonverifiable_get_raw_duration_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "# of blocks per second (tm: 0.2 b/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(tendermint_consensus_latest_block_height[5m])"
    }
   ]
  },
  {
   "title": "Storage lookups (jmt)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(penumbra_storage_get_raw_duration_seconds_sum[5m]) / rate(penumbra_storage_get_raw_duration_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Height (tm)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "tendermint_consensus_height" }
   ]
  },
  {
   "title": "Nonverif # count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(penumbra_storage_nonverifiable_get_raw_duration_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "JMT # count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(penumbra_storage_get_raw_duration_seconds_count[5m])"
    }
   ]
  }
 ]
}