[package]
name = "elcuity"
version = {workspace = true}
authors = {workspace = true}
edition = {workspace = true}
description = "Tool for liquidity tournament related testing"
repository = {workspace = true}
homepage = {workspace = true}
license = {workspace = true}
publish = false

[package.metadata.dist]
dist = true

[dependencies]
anyhow = {workspace = true}
async-stream = {workspace = true}
clap = {workspace = true, features = ["derive", "env"]}
decaf377 = {workspace = true}
futures = {workspace = true}
penumbra-sdk-asset = {workspace = true}
penumbra-sdk-custody = {workspace = true}
penumbra-sdk-dex = {workspace = true}
penumbra-sdk-fee = {workspace = true}
penumbra-sdk-keys = {workspace = true}
penumbra-sdk-num = {workspace = true}
penumbra-sdk-transaction = {workspace = true}
penumbra-sdk-proto = {workspace = true, features = ["rpc", "box-grpc"], default-features = true}
penumbra-sdk-view = {workspace = true}
rand_core = {workspace = true}
rustls = {workspace = true}
tokio = {workspace = true}
tonic = {workspace = true}
tracing = {workspace = true}
tracing-subscriber = {workspace = true, features = ["env-filter"]}
